/**
 * Dummy Data Generator
 * Provides sample loan application data for development/testing
 */

import type { ApplicationData } from '@/lib/applicationStore';

/**
 * Sample loan application data for testing
 */
export const dummyApplicationData: ApplicationData = {
  projectOverview: {
    projectName: 'ABC Manufacturing Acquisition',
    projectDescription:
      'Acquisition of an established precision manufacturing business specializing in aerospace components. The target company has been in operation for 25 years with a strong customer base including Boeing, Lockheed Martin, and several Tier 1 aerospace suppliers. The acquisition will include all equipment, inventory, customer contracts, and the existing workforce of 45 employees.',
    bdoName: 'John Smith',
    bdaName: 'Sarah Johnson',
    bdo1: 'John Smith',
    bdo2: 'Mike Williams',
    bda: 'Sarah Johnson',
    industry: 'Manufacturing',
    naicsCode: '332710',
    primaryProjectPurpose: ['Business Acquisition'],
    riskRepayment: 3,
    riskManagement: 4,
    riskEquity: 3,
    riskCollateral: 4,
    riskCredit: 3,
    riskLiquidity: 3,
  },
  sourcesUses: {
    // Legacy flat fields
    loanAmount: 1500000,
    sellerFinancing: 200000,
    equityInjection: 300000,
    otherSources: 0,
    totalSources: 2000000,
    purchasePrice: 1800000,
    workingCapital: 150000,
    closingCosts: 50000,
    contingency: 0,
    otherUses: 0,
    totalUses: 2000000,
    gap: 0,
    // Matrix data - Sources & Uses by category
    businessAcquisition: {
      tBankLoan: 1350000,
      borrower: 270000,
      sellerNote: 180000,
      thirdParty: 0,
    },
    workingCapitalMatrix: {
      tBankLoan: 125000,
      borrower: 15000,
      sellerNote: 10000,
      thirdParty: 0,
    },
    closingCostsMatrix: {
      tBankLoan: 25000,
      borrower: 15000,
      sellerNote: 10000,
      thirdParty: 0,
    },
    realEstate: {
      tBankLoan: 0,
      borrower: 0,
      sellerNote: 0,
      thirdParty: 0,
    },
    debtRefiCRE: {
      tBankLoan: 0,
      borrower: 0,
      sellerNote: 0,
      thirdParty: 0,
    },
    debtRefiNonCRE: {
      tBankLoan: 0,
      borrower: 0,
      sellerNote: 0,
      thirdParty: 0,
    },
    equipment: {
      tBankLoan: 0,
      borrower: 0,
      sellerNote: 0,
      thirdParty: 0,
    },
    furnitureFixtures: {
      tBankLoan: 0,
      borrower: 0,
      sellerNote: 0,
      thirdParty: 0,
    },
    inventory: {
      tBankLoan: 0,
      borrower: 0,
      sellerNote: 0,
      thirdParty: 0,
    },
    other: {
      tBankLoan: 0,
      borrower: 0,
      sellerNote: 0,
      thirdParty: 0,
    },
  },
  // Table-specific Sources & Uses data
  sourcesUses7a: {
    loanAmount: 1500000,
    sellerFinancing: 200000,
    equityInjection: 300000,
    otherSources: 0,
    totalSources: 2000000,
    purchasePrice: 1800000,
    workingCapital: 150000,
    closingCosts: 50000,
    contingency: 0,
    otherUses: 0,
    totalUses: 2000000,
    gap: 0,
    businessAcquisition: {
      tBankLoan: 1350000,
      borrower: 270000,
      sellerNote: 180000,
      thirdParty: 0,
    },
  },
  sourcesUses504: {
    loanAmount: 0,
    sellerFinancing: 0,
    equityInjection: 0,
    otherSources: 0,
    totalSources: 0,
    purchasePrice: 0,
    workingCapital: 0,
    closingCosts: 0,
    contingency: 0,
    otherUses: 0,
    totalUses: 0,
    gap: 0,
  },
  sourcesUsesExpress: {
    loanAmount: 0,
    sellerFinancing: 0,
    equityInjection: 0,
    otherSources: 0,
    totalSources: 0,
    purchasePrice: 0,
    workingCapital: 0,
    closingCosts: 0,
    contingency: 0,
    otherUses: 0,
    totalUses: 0,
    gap: 0,
  },
  loan1: {
    type: 'SBA 7(a)',
    amount: 1500000,
    term: 10,
    baseRate: 'Prime',
    spread: 2.75,
    totalRate: 10.25,
    monthlyPayment: 20125,
    loanAmount: 1500000,
    interestRate: 10.25,
    termMonths: 120,
    amortizationMonths: 120,
    paymentFrequency: 'monthly',
    paymentAmount: 20125,
  },
  loan2: {
    type: 'Seller Note',
    amount: 200000,
    term: 5,
    totalRate: 6.0,
    monthlyPayment: 3867,
    loanAmount: 200000,
    interestRate: 6.0,
    termMonths: 60,
    amortizationMonths: 60,
    paymentFrequency: 'monthly',
    paymentAmount: 3867,
  },
  dscr: {
    period1: '2023',
    period2: '2024',
    period3: '2025',
    period4: 'Interim',
    dscr1: 1.25,
    dscr2: 1.35,
    dscr3: 1.45,
    dscr4: 1.50,
  },
  individualApplicants: [
    {
      id: 'applicant-1',
      firstName: 'Jane',
      lastName: 'Doe',
      email: 'jane.doe@email.com',
      phone: '(555) 123-4567',
      dateOfBirth: '1975-06-15',
      ssn: '123-45-6789',
      ownershipPercentage: 51,
      address: {
        street1: '456 Oak Avenue',
        street2: 'Suite 100',
        city: 'Dallas',
        state: 'TX',
        zipCode: '75201',
      },
      homeAddress: {
        street1: '789 Maple Drive',
        city: 'Plano',
        state: 'TX',
        zipCode: '75024',
      },
      role: 'Managing Member',
      title: 'CEO',
      ownershipType: 'Direct',
      projectRole: 'Operating Company',
      businessRole: 'Active',
      businessRoleDescription: 'Day-to-day management and strategic planning',
      experience:
        '20 years of manufacturing industry experience including 10 years in aerospace sector',
      yearsOfExperience: '20',
      creditScore: '750',
      travelTime: '15 minutes',
      netWorth: '1500000',
      pcLiquidity: '350000',
      reqDraw: '150000',
      equityInjectionAmount: '200000',
    },
    {
      id: 'applicant-2',
      firstName: 'Robert',
      lastName: 'Smith',
      email: 'robert.smith@email.com',
      phone: '(555) 987-6543',
      dateOfBirth: '1980-03-22',
      ssn: '987-65-4321',
      ownershipPercentage: 49,
      address: {
        street1: '321 Pine Street',
        city: 'Dallas',
        state: 'TX',
        zipCode: '75202',
      },
      homeAddress: {
        street1: '654 Elm Court',
        city: 'Frisco',
        state: 'TX',
        zipCode: '75034',
      },
      role: 'Member',
      title: 'COO',
      ownershipType: 'Direct',
      projectRole: 'Operating Company',
      businessRole: 'Active',
      businessRoleDescription: 'Operations management and quality control',
      experience:
        '15 years in operations management with focus on lean manufacturing',
      yearsOfExperience: '15',
      creditScore: '720',
      travelTime: '20 minutes',
      netWorth: '800000',
      pcLiquidity: '150000',
      reqDraw: '120000',
      equityInjectionAmount: '100000',
    },
  ],
  businessApplicant: {
    id: 'business-1',
    legalName: 'ABC Holdings LLC',
    dba: 'ABC Manufacturing',
    ein: '12-3456789',
    entityType: 'LLC',
    formationDate: '2024-01-15',
    stateOfFormation: 'Texas',
    address: {
      street1: '123 Industrial Parkway',
      city: 'Dallas',
      state: 'TX',
      zipCode: '75201',
    },
    phone: '(555) 555-1234',
    email: 'info@abcholdings.com',
    website: 'www.abcmanufacturing.com',
    industryType: 'Manufacturing',
    naicsCode: '332710',
    entityToBeFormed: false,
    sameAsSubjectBusiness: false,
    yearsInOperation: 0,
    dbaName: 'ABC Manufacturing',
    yearEstablished: '2024',
    existingEmployees: '0',
    jobsSavedRetained: '45',
    newFTEJobsCreated: '5',
    businessAddress: {
      street1: '123 Industrial Parkway',
      city: 'Dallas',
      state: 'TX',
      zipCode: '75201',
    },
    projectAddress: {
      street1: '123 Industrial Parkway',
      city: 'Dallas',
      state: 'TX',
      zipCode: '75201',
    },
  },
  sbaEligibility: {
    isSmallBusiness: true,
    hasDisqualifyingBackground: false,
    hasDelinquentDebt: false,
    hasBankruptcy: false,
    hasJudgments: false,
    hasLiens: false,
    isInGoodStanding: true,
    meetsNetWorthRequirement: true,
    meetsIncomeRequirement: true,
    additionalNotes: 'All principals have clean backgrounds and no derogatory items.',
  },
  sellerInfo: {
    businessName: 'ABC Manufacturing Inc.',
    legalName: 'ABC Manufacturing Inc.',
    sellerName: 'William Anderson',
    sellerAddress: {
      street1: '123 Industrial Parkway',
      city: 'Dallas',
      state: 'TX',
      zipCode: '75201',
    },
    sellerPhone: '(555) 444-3333',
    sellerEmail: 'wanderson@abcmfg.com',
    businessDescription:
      'Established precision manufacturing company specializing in aerospace components',
    yearsInBusiness: 25,
    reasonForSale: 'Retirement - owner is 68 years old and ready to retire',
    website: 'www.abcmanufacturing.com',
    contactName: 'William Anderson',
    contactPhone: '(555) 444-3333',
    contactEmail: 'wanderson@abcmfg.com',
  },
  personalFinancialStatements: {},
  otherOwnedBusinesses: {
    hasOtherBusinesses: null,
    businesses: [],
  },
  feeDisclosure: null,
  financingSources: [],
  uploadedFiles: [],
};

/**
 * Function to get dummy data for populating the application store
 */
export function getDummyApplicationData(): ApplicationData {
  return { ...dummyApplicationData };
}
