/**
 * Human-readable labels for audit log field paths.
 * Used by diffObjects() to produce friendly change descriptions.
 */

export const FIELD_LABELS: Record<string, string> = {
  // --- Project ---
  projectName: 'Project Name',
  businessName: 'Business Name',
  stage: 'Project Stage',
  status: 'Project Status',
  loanAmount: 'Loan Amount',
  businessType: 'Business Type',
  location: 'Location',
  bdoUserId: 'Assigned BDO (ID)',
  bdoUserName: 'Assigned BDO',
  borrowerUserId: 'Borrower User ID',
  sharepointFolderId: 'SharePoint Folder ID',
  sharepointFolderUrl: 'SharePoint Folder URL',
  primarySpreadId: 'Primary Spread',
  deletedAt: 'Deleted At',
  deletedBy: 'Deleted By',

  // --- Project Overview ---
  'projectOverview.projectName': 'Project Name',
  'projectOverview.bdoName': 'BDO Name',
  'projectOverview.bdaName': 'BDA Name',
  'projectOverview.bdo1': 'BDO 1',
  'projectOverview.bdo2': 'BDO 2',
  'projectOverview.bda': 'BDA',
  'projectOverview.referralSource': 'Referral Source',
  'projectOverview.referralIndividual': 'Referral Individual',
  'projectOverview.referralFirm': 'Referral Firm',
  'projectOverview.referralFee': 'Referral Fee',
  'projectOverview.industry': 'Industry',
  'projectOverview.naicsCode': 'NAICS Code',
  'projectOverview.primaryProjectPurpose': 'Primary Project Purpose',
  'projectOverview.secondaryProjectPurposes': 'Secondary Project Purposes',
  'projectOverview.projectDescription': 'Project Description',
  'projectOverview.goodFitSummary': 'Good Fit Summary',
  'projectOverview.loanWeaknesses': 'Loan Weaknesses',
  'projectOverview.affiliatesCorporateGuarantors': 'Affiliates / Corporate Guarantors',
  'projectOverview.bdoComments': 'BDO Comments',
  'projectOverview.riskRepayment': 'Risk Score: Repayment',
  'projectOverview.riskManagement': 'Risk Score: Management',
  'projectOverview.riskEquity': 'Risk Score: Equity',
  'projectOverview.riskCollateral': 'Risk Score: Collateral',
  'projectOverview.riskCredit': 'Risk Score: Credit',
  'projectOverview.riskLiquidity': 'Risk Score: Liquidity',
  'projectOverview.computedProjectType': 'Computed Project Type',
  'projectOverview.computedRiskLevel': 'Computed Risk Level',

  // --- Business Applicant ---
  'businessApplicant.legalName': 'Business Legal Name',
  'businessApplicant.dba': 'Business DBA',
  'businessApplicant.dbaName': 'Business DBA Name',
  'businessApplicant.ein': 'Business EIN',
  'businessApplicant.entityType': 'Entity Type',
  'businessApplicant.formationDate': 'Formation Date',
  'businessApplicant.stateOfFormation': 'State of Formation',
  'businessApplicant.phone': 'Business Phone',
  'businessApplicant.email': 'Business Email',
  'businessApplicant.website': 'Business Website',
  'businessApplicant.industryType': 'Industry Type',
  'businessApplicant.naicsCode': 'Business NAICS Code',
  'businessApplicant.yearEstablished': 'Year Established',
  'businessApplicant.existingEmployees': 'Existing Employees',
  'businessApplicant.jobsSavedRetained': 'Jobs Saved/Retained',
  'businessApplicant.newFTEJobsCreated': 'New FTE Jobs Created',
  'businessApplicant.address.street1': 'Business Street Address',
  'businessApplicant.address.city': 'Business City',
  'businessApplicant.address.state': 'Business State',
  'businessApplicant.address.zipCode': 'Business ZIP Code',
  'businessApplicant.projectAddress.street1': 'Project Street Address',
  'businessApplicant.projectAddress.city': 'Project City',
  'businessApplicant.projectAddress.state': 'Project State',
  'businessApplicant.projectAddress.zipCode': 'Project ZIP Code',

  // --- Individual Applicant (generic — array items use dynamic labels) ---
  firstName: 'First Name',
  middleName: 'Middle Name',
  lastName: 'Last Name',
  suffix: 'Suffix',
  email: 'Email',
  phone: 'Phone',
  dateOfBirth: 'Date of Birth',
  ssn: 'SSN',
  ownershipPercentage: 'Ownership %',
  role: 'Role',
  title: 'Title',
  gender: 'Gender',
  ownershipType: 'Ownership Type',
  projectRole: 'Project Role',
  businessRole: 'Business Role',
  businessRoleDescription: 'Business Role Description',
  experience: 'Experience',
  yearsOfExperience: 'Years of Experience',
  creditScore: 'Credit Score',
  estimatedCreditScore: 'Estimated Credit Score',
  creditScoreExplanation: 'Credit Score Explanation',
  travelTime: 'Travel Time',
  planToBeOnSite: 'Plan to Be On-Site',
  netWorth: 'Net Worth',
  pcLiquidity: 'Post-Closing Liquidity',
  reqDraw: 'Required Draw',
  equityInjectionAmount: 'Equity Injection Amount',
  'address.street1': 'Street Address',
  'address.city': 'City',
  'address.state': 'State',
  'address.zipCode': 'ZIP Code',

  // --- Seller Info ---
  'sellerInfo.businessName': 'Seller Business Name',
  'sellerInfo.legalName': 'Seller Legal Name',
  'sellerInfo.sellerName': 'Seller Contact Name',
  'sellerInfo.sellerPhone': 'Seller Phone',
  'sellerInfo.sellerEmail': 'Seller Email',
  'sellerInfo.businessDescription': 'Seller Business Description',
  'sellerInfo.yearsInBusiness': 'Seller Years in Business',
  'sellerInfo.reasonForSale': 'Reason for Sale',
  'sellerInfo.website': 'Seller Website',
  'sellerInfo.purchasePrice': 'Purchase Price',
  'sellerInfo.typeOfAcquisition': 'Type of Acquisition',
  'sellerInfo.purchasing100Percent': 'Purchasing 100%',
  'sellerInfo.purchaseContractStatus': 'Purchase Contract Status',
  'sellerInfo.hasSellerCarryNote': 'Has Seller Carry Note',
  'sellerInfo.sellerCarryNoteTerms': 'Seller Carry Note Terms',
  'sellerInfo.realEstatePurchaseDescription': 'Real Estate Purchase Description',

  // --- SBA Eligibility ---
  'sbaEligibility.convicted': 'Convicted of a Crime',
  'sbaEligibility.arrested': 'Currently Under Arrest/Charge',
  'sbaEligibility.pendingLawsuits': 'Pending Lawsuits',
  'sbaEligibility.childSupport': 'Child Support Obligations',
  'sbaEligibility.taxLiens': 'Tax Liens',
  'sbaEligibility.bankruptcy': 'Bankruptcy History',
  'sbaEligibility.federalDebt': 'Federal Debt',
  'sbaEligibility.nonCitizenOwner': 'Non-Citizen Owner',
  'sbaEligibility.eligibilityExplanation': 'Eligibility Explanation',
  'sbaEligibility.convictedExplanation': 'Convicted Explanation',
  'sbaEligibility.arrestedExplanation': 'Arrested Explanation',
  'sbaEligibility.pendingLawsuitsExplanation': 'Pending Lawsuits Explanation',
  'sbaEligibility.childSupportExplanation': 'Child Support Explanation',
  'sbaEligibility.taxLiensExplanation': 'Tax Liens Explanation',
  'sbaEligibility.bankruptcyExplanation': 'Bankruptcy Explanation',
  'sbaEligibility.federalDebtExplanation': 'Federal Debt Explanation',

  // --- Sources & Uses (legacy flat) ---
  'sourcesUses.loanAmount': 'Loan Amount',
  'sourcesUses.sellerFinancing': 'Seller Financing',
  'sourcesUses.equityInjection': 'Equity Injection',
  'sourcesUses.otherSources': 'Other Sources',
  'sourcesUses.totalSources': 'Total Sources',
  'sourcesUses.purchasePrice': 'Purchase Price',
  'sourcesUses.workingCapital': 'Working Capital',
  'sourcesUses.closingCosts': 'Closing Costs',
  'sourcesUses.contingency': 'Contingency',
  'sourcesUses.otherUses': 'Other Uses',
  'sourcesUses.totalUses': 'Total Uses',
  'sourcesUses.gap': 'Sources/Uses Gap',

  // --- Loan Details ---
  'loan1.type': 'Loan 1 Type',
  'loan1.amount': 'Loan 1 Amount',
  'loan1.term': 'Loan 1 Term',
  'loan1.baseRate': 'Loan 1 Base Rate',
  'loan1.spread': 'Loan 1 Spread',
  'loan1.totalRate': 'Loan 1 Total Rate',
  'loan2.type': 'Loan 2 Type',
  'loan2.amount': 'Loan 2 Amount',
  'loan2.term': 'Loan 2 Term',
  'loan2.baseRate': 'Loan 2 Base Rate',
  'loan2.spread': 'Loan 2 Spread',
  'loan2.totalRate': 'Loan 2 Total Rate',

  // --- DSCR ---
  'dscr.period1': 'DSCR Period 1',
  'dscr.period2': 'DSCR Period 2',
  'dscr.period3': 'DSCR Period 3',
  'dscr.period4': 'DSCR Period 4',
  'dscr.dscr1': 'DSCR Ratio 1',
  'dscr.dscr2': 'DSCR Ratio 2',
  'dscr.dscr3': 'DSCR Ratio 3',
  'dscr.dscr4': 'DSCR Ratio 4',

  // --- Other Owned Businesses ---
  'otherOwnedBusinesses.hasOtherBusinesses': 'Has Other Businesses',

  // --- Financing Sources (array — individual items use dynamic labels) ---
  financingType: 'Financing Type',
  guaranteePercent: 'Guarantee %',
  amount: 'Amount',
  rateType: 'Rate Type',
  termYears: 'Term (Years)',
  amortizationMonths: 'Amortization (Months)',
  baseRate: 'Base Rate',
  spread: 'Spread',
  totalRate: 'Total Rate',

  // --- Risk Classification ---
  'projectOverview.classification.businessStage': 'Business Stage',
  'projectOverview.classification.ownershipChange': 'Ownership Change',
  'projectOverview.classification.creComponent': 'CRE Component',
  'projectOverview.classification.debtRefinance': 'Debt Refinance',
  'projectOverview.classification.riskLevelOverride': 'Risk Level Override',
};
