'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { authenticatedFetch } from '@/lib/authenticatedFetch';
import type { DiligencePhase } from '@/hooks/useDiligenceReport';

export interface SbaPrescreenResult {
  reportText: string;
  model: string;
  generatedAt: string;
  pdfName?: string;
  excelName?: string;
  excelTruncated?: boolean;
  hasDocument?: boolean;
}

export interface SbaPrescreenDocument {
  filename: string;
  /** Base64-encoded .docx bytes generated by the agent. */
  data: string;
}

interface UseSbaPrescreenResult {
  result: SbaPrescreenResult | null;
  document: SbaPrescreenDocument | null;
  isStreaming: boolean;
  phase: DiligencePhase;
  streamedText: string;
  error: string | null;
  generate: (pdf: File, excel: File) => Promise<void>;
}

// Display-only streaming hook for the SBA Prescreen admin tab, modeled on
// useInternalDdTest. Uploads the two documents as multipart form data and
// consumes the /api/sba-prescreen ndjson stream. No persistence, no
// reconnect: aborting (unmount / rerun) genuinely cancels the agent run.
export function useSbaPrescreen(): UseSbaPrescreenResult {
  const [result, setResult] = useState<SbaPrescreenResult | null>(null);
  const [document, setDocument] = useState<SbaPrescreenDocument | null>(null);
  const [isStreaming, setIsStreaming] = useState<boolean>(false);
  const [phase, setPhase] = useState<DiligencePhase>(null);
  const [streamedText, setStreamedText] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  const abortRef = useRef<AbortController | null>(null);
  const isStreamingRef = useRef(false);

  useEffect(() => {
    return () => {
      abortRef.current?.abort();
    };
  }, []);

  const generate = useCallback(async (pdf: File, excel: File) => {
    if (isStreamingRef.current) return;

    const controller = new AbortController();
    abortRef.current?.abort();
    abortRef.current = controller;

    isStreamingRef.current = true;
    setIsStreaming(true);
    setError(null);
    setResult(null);
    setDocument(null);
    setStreamedText('');
    setPhase('thinking');

    try {
      const formData = new FormData();
      formData.append('pdf', pdf);
      formData.append('excel', excel);

      const res = await authenticatedFetch('/api/sba-prescreen', {
        method: 'POST',
        body: formData,
        signal: controller.signal,
      });

      if (!res.ok || !res.body) {
        let message = `Prescreen failed (${res.status})`;
        try {
          const errBody = await res.json();
          if (errBody?.error) message = errBody.error;
        } catch {
          // ignore
        }
        throw new Error(message);
      }

      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });

        let newlineIdx: number;
        while ((newlineIdx = buffer.indexOf('\n')) !== -1) {
          const line = buffer.slice(0, newlineIdx).trim();
          buffer = buffer.slice(newlineIdx + 1);
          if (!line) continue;
          let evt: any;
          try {
            evt = JSON.parse(line);
          } catch {
            continue;
          }
          switch (evt.type) {
            case 'reset':
              setStreamedText('');
              break;
            case 'phase':
              setPhase(evt.phase ?? null);
              break;
            case 'text':
              if (typeof evt.text === 'string') {
                setStreamedText((prev) => prev + evt.text);
              }
              break;
            case 'error':
              setError(evt.error || 'Prescreen failed');
              break;
            case 'file':
              if (typeof evt.data === 'string' && evt.data) {
                setDocument({
                  filename:
                    typeof evt.filename === 'string' && evt.filename
                      ? evt.filename
                      : 'prescreen.docx',
                  data: evt.data,
                });
              }
              break;
            case 'done':
              setResult({
                reportText: evt.reportText || '',
                model: evt.model || '',
                generatedAt: evt.generatedAt || new Date().toISOString(),
                pdfName: evt.pdfName,
                excelName: evt.excelName,
                excelTruncated: evt.excelTruncated,
                hasDocument: evt.hasDocument,
              });
              break;
          }
        }
      }
    } catch (err: any) {
      if (err?.name === 'AbortError') return;
      console.error('[useSbaPrescreen] Stream failed:', err);
      setError(err?.message || 'Failed to run the prescreen');
    } finally {
      isStreamingRef.current = false;
      setIsStreaming(false);
      setPhase(null);
    }
  }, []);

  return {
    result,
    document,
    isStreaming,
    phase,
    streamedText,
    error,
    generate,
  };
}
