import { SbaFormMapping } from './types';

/**
 * SBA Form 413 - Personal Financial Statement
 * This form collects personal financial information from business owners
 */
export const sba413Mapping: SbaFormMapping = {
  formId: 'sba-413',
  formName: 'SBA Form 413 - Personal Financial Statement',
  formNumber: '413',
  fieldSignatures: [
    'PERSONAL FINANCIAL STATEMENT',
    'ASSETS',
    'LIABILITIES',
    'Net Worth',
    'Cash on hand',
    'Savings Accounts',
    'Notes Payable',
  ],
  mappings: [
    // Personal Information
    {
      pdfFieldName: 'Name',
      appSection: 'individualApplicants',
      appFieldPath: 'owners[0].fullName',
      confidence: 0.9,
      label: 'Full Name',
    },
    {
      pdfFieldName: 'Residence Address',
      appSection: 'individualApplicants',
      appFieldPath: 'owners[0].address.street1',
      confidence: 0.85,
      label: 'Residence Address',
    },
    {
      pdfFieldName: 'City State Zip',
      appSection: 'individualApplicants',
      appFieldPath: 'owners[0].address.cityStateZip',
      confidence: 0.8,
      label: 'City, State, ZIP',
    },
    {
      pdfFieldName: 'Business Phone',
      appSection: 'individualApplicants',
      appFieldPath: 'owners[0].businessPhone',
      transform: 'phone',
      confidence: 0.85,
      label: 'Business Phone',
    },
    {
      pdfFieldName: 'Residence Phone',
      appSection: 'individualApplicants',
      appFieldPath: 'owners[0].homePhone',
      transform: 'phone',
      confidence: 0.85,
      label: 'Residence Phone',
    },
    // Assets
    {
      pdfFieldName: 'Cash on hand',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.cashOnHand',
      transform: 'currency',
      confidence: 0.9,
      label: 'Cash on Hand',
    },
    {
      pdfFieldName: 'Savings Accounts',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.savingsAccounts',
      transform: 'currency',
      confidence: 0.9,
      label: 'Savings Accounts',
    },
    {
      pdfFieldName: 'IRA or Other Retirement',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.retirementAccounts',
      transform: 'currency',
      confidence: 0.9,
      label: 'Retirement Accounts',
    },
    {
      pdfFieldName: 'Accounts Receivable',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.accountsReceivable',
      transform: 'currency',
      confidence: 0.85,
      label: 'Accounts Receivable',
    },
    {
      pdfFieldName: 'Life Insurance Cash Value',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.lifeInsuranceCashValue',
      transform: 'currency',
      confidence: 0.9,
      label: 'Life Insurance Cash Value',
    },
    {
      pdfFieldName: 'Stocks and Bonds',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.stocksAndBonds',
      transform: 'currency',
      confidence: 0.9,
      label: 'Stocks and Bonds',
    },
    {
      pdfFieldName: 'Real Estate',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.realEstate',
      transform: 'currency',
      confidence: 0.9,
      label: 'Real Estate',
    },
    {
      pdfFieldName: 'Automobiles',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.automobiles',
      transform: 'currency',
      confidence: 0.85,
      label: 'Automobiles',
    },
    {
      pdfFieldName: 'Other Assets',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.otherAssets',
      transform: 'currency',
      confidence: 0.8,
      label: 'Other Assets',
    },
    {
      pdfFieldName: 'Total Assets',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'assets.totalAssets',
      transform: 'currency',
      confidence: 0.95,
      label: 'Total Assets',
    },
    // Liabilities
    {
      pdfFieldName: 'Accounts Payable',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'liabilities.accountsPayable',
      transform: 'currency',
      confidence: 0.9,
      label: 'Accounts Payable',
    },
    {
      pdfFieldName: 'Notes Payable',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'liabilities.notesPayable',
      transform: 'currency',
      confidence: 0.9,
      label: 'Notes Payable',
    },
    {
      pdfFieldName: 'Installment Account',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'liabilities.installmentAccounts',
      transform: 'currency',
      confidence: 0.85,
      label: 'Installment Accounts',
    },
    {
      pdfFieldName: 'Mortgages on Real Estate',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'liabilities.mortgages',
      transform: 'currency',
      confidence: 0.9,
      label: 'Mortgages',
    },
    {
      pdfFieldName: 'Unpaid Taxes',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'liabilities.unpaidTaxes',
      transform: 'currency',
      confidence: 0.9,
      label: 'Unpaid Taxes',
    },
    {
      pdfFieldName: 'Other Liabilities',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'liabilities.otherLiabilities',
      transform: 'currency',
      confidence: 0.8,
      label: 'Other Liabilities',
    },
    {
      pdfFieldName: 'Total Liabilities',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'liabilities.totalLiabilities',
      transform: 'currency',
      confidence: 0.95,
      label: 'Total Liabilities',
    },
    {
      pdfFieldName: 'Net Worth',
      appSection: 'personalFinancialStatement',
      appFieldPath: 'netWorth',
      transform: 'currency',
      confidence: 0.95,
      label: 'Net Worth',
    },
  ],
};
